### ISSUE TITLE
Suggestion about catch() { }

### ISSUE THREAD

**Issue by jcampbell1710** [panzerdp/dmitripavlutin.com#40]
Good article!  But I think a clarification is necessary.  Because you don't suggest a way to provide exception handling when there is just a `return`, it is easy to get the impression that the failure to catch means you should *always* do `return await`.  This is not so. 

Because `await` is needed only when the final result has to be accessed, which is not ever when returning a value from a function, `return await` usually should be avoided.  In fact, because an asynchronous function *always* returns a Promise object whether or not `await` is used, the function caller is stuck having to do `await` anyway.  The net is that your application will be needlessly slowed down, since every `await` forces the asynchronous thread to return results to the caller.  In fact, you will find linting environments that give you a warning when you do `return await`.  

The bottom line is that only one `await` over the whole thing is usually all that is necessary. The last `await` will resolve all the pending promises in application, whether or not there are exceptions.

You can always do a `try`/`catch` to surround the caller.

```
async function divideWithoutAwait() {
    return promisedDivision(5, 0);
}

async function run() {
  try {
    const result = await divideWithoutAwait();
  } catch (error) {
    // Rejection  caught!
    console.log(error);
  }
}
run(); // Cannot divide by 0
```

or if you prefer to leave the exception handling in the method:
```
async function divideWithoutAwait() {
    return promisedDivision(5, 0).catch((err) => { console.log(err); });
}

async function run() {
  const result = await divideWithoutAwait();
  return result;
}

run(); // Cannot divide by 0
```

**Comment by panzerdp** [comment]
Thanks for sharing your thoughts. If you’d like to improve the post, feel free to create a pull request.
