### ISSUE TITLE
Recommend use of built-in Record<> in TypeScript instead of index signature syntax

### ISSUE THREAD

**Issue by schontz** [panzerdp/dmitripavlutin.com#47]
From this post: https://dmitripavlutin.com/typescript-index-signatures/

All those types can simply be replaced with the built-in `Record<key, value>` generic type:

```ts
const dictionary: Record<string, number> = {
  one: 1,
  two: 2,
  three: 3
}

for (const name in dictionary) {
  const num = dictionary[name]
}
```

**Comment by panzerdp** [comment]
I've updated the post to show the difference between index signatures and Record utility. See this [section](https://dmitripavlutin.com/typescript-index-signatures/#4-index-signature-vs-recordkeys-type).

**Comment by schontz** [comment]
Interesting update. But it would be worth noting that you can always do:

```ts
type StringByString = Record<string, string>
```

For what it's worth, here is the actual TypeScript implementation:

```ts
/**
 * Construct a type with a set of properties K of type T
 */
type Record<K extends keyof any, T> = {
    [P in K]: T;
};
```

I'm not that clear where it would be worth defining `interface { [key: K]: V }` when `Record<K, V>` will always give you the same thing in a more concise manner, and with the added flexibility of constraining the type further, as your updated section details.

Why would you recommend the former when the latter does all that and more? Does it just come down to style and personal preference?

And isn't the challenge at the end for `Indexed<K, V>` just asking someone to write `Record<K, V>`?

I'm asking these in a genuine way since people are always looking for good advice on blog posts. If the best tool for the job is `Record`, we should just tell people that at the outset, and deep dive into alternatives and underlaying reasons to help educate. You and I may be clear how all these things work, but for the newer folks that run into that error and search for answers, let's give them them the best answer straight away.
