### ISSUE TITLE
Unable to run the project locally.

### ISSUE THREAD

**Issue by Sathyamurthy-tammina** [panzerdp/dmitripavlutin.com#54]
I get the following error on trying run the project locally. I used the command "npm run dev". Thanks

![image](https://user-images.githubusercontent.com/62736458/140261931-3b8e044c-ff15-4f79-8dab-731be3b58994.png)

**Comment by panzerdp** [comment]
You need a Mailchimp API key to run the build. Try to disable the mailchimp plugin.
