### ISSUE TITLE
multiply wants to do too many things

### ISSUE THREAD

**Issue by rkrisztian** [panzerdp/dmitripavlutin.com#68]
Quoting from:

https://dmitripavlutin.com/when-not-to-use-arrow-functions-in-javascript/

This function is a good example of breaking the single responsibility principle:

```javascript
const multiply = (a, b) => b === undefined ? b => a * b : a * b;
```

Which your guide would rewrite to:

```javascript
function multiply(a, b) {
  if (b === undefined) {
    return function(b) {
      return a * b;
    }
  }
  return a * b;
}
```

Here the problem is not that we shouldn't use arrow functions. The problem is we shouldn't write such code at all:

* The name of the function is misleading. It could be called `multiplyOrCurry` or something like that, but that's the problem. The "And" or "Or" in function names is less disinformative, so that's better, but at the same time, now we see clearer that we are breaking the SRP.
* This is how currying should be done: https://javascript.info/currying-partials .
* The arrow function is only harder to read because it's too complex in the first place.

I know you probably wanted to show a fine example there because our gut feeling is that there should be some code out there that could be a proper example for when arrow functions are indeed hard to read. And indeed, the conditional operator (or also called ternary operator), is also often judged because it's too short, which especially hurts during nesting. Here we nest the conditional operator with the arrow, which in complexity is very similar to the nesting problem. Other than that, right now I can't give you a better example. But we surely shouldn't leave the documentation as it is.

**Comment by panzerdp** [comment]
Thanks for sharing your opinion. The only goal is to show when an arrow function is harder to read.

**Comment by rkrisztian** [comment]
As I said, you surely shouldn't leave the documentation as it is, and I still think so because you're failing to make your point, because you're blaming the arrow function when in fact that's not the problem in the example, but too many other things: nesting too many operators (and not even adding helper parentheses), as well as giving a function a misleading name. So you should pick a different example.

As for your rewrite, arrow functions are not always bad, e.g., see this:

```javascript
function multiply(a, b) {
  if (b === undefined) {
    return (b) => a * b;
  }
  return a * b;
}
```

I'm just trying to make the world a better place, but the world does not want to get better, that's sad.
