### ISSUE TITLE
Optional parameter fix for code example in "When to use function overloading"

### ISSUE THREAD

**Issue by joshden** [panzerdp/dmitripavlutin.com#70]
The last code example in https://dmitripavlutin.com/typescript-function-overloading/ (which I believe is this markdown: https://github.com/panzerdp/dmitripavlutin.com/blob/master/content/posts/158-ts-function-overloading/index.md) is missing the `?` for the second parameter `param2`. I believe it should be as follows:

```
// OK
function myFunc(param1?: string, param2?: string): string {
  // implementation...
}
```

**Comment by panzerdp** [comment]
@joshden Feel free to create a pull request with the change.

**Comment by panzerdp** [comment]
Fixed. :)
