### ISSUE TITLE
404 hyperlink in `Gentle Explanation of "this"`

### ISSUE THREAD

**Issue by aryanshridhar** [panzerdp/dmitripavlutin.com#72]
Hey,
Thanks for the amazing post regarding the `this` keyword in javascript. Super helpful!

Just noticed that the `factory pattern` javascript.info link throws a 404 error within https://dmitripavlutin.com/gentle-explanation-of-this-in-javascript/#42-pitfall-forgetting-about-new.

Link - https://javascript.info/class-patterns.
Not sure where was this resource moved.

**Comment by panzerdp** [comment]
Hey Aryan! Glad you like the post!

I've update the post to link to a different article on factory pattern.

Thanks!
