### ISSUE TITLE
Gentle Explanation of "this" / "3.2 Pitfall :separating method from its object"

### ISSUE THREAD

**Issue by adolfo92** [panzerdp/dmitripavlutin.com#81]
```js
function Pet(type, legs) {
  this.type = type;
  this.legs = legs;
  this.logInfo = function() {
    console.log(this === myCat); // => false
    console.log(`The $ {this.type} has $ {this.legs} legs`);
  }
}
const myCat = new Pet('Cat', 4);
// logs "The undefined has undefined legs"
// or throws a TypeError in strict mode
setTimeout(myCat.logInfo, 1000);
```

In that piece of code, you said that the `console.log(this === myCat)` statement would return `false`, but it's actually returning `true` because `logInfo` is still taking the Pet object as context.

This is the first code example on that part.

**Comment by adolfo92** [comment]
Whoops, i realized my mistake, sorry about this.

**Comment by panzerdp** [comment]
> Whoops, i realized my mistake, sorry about this.

Seems like `this` tricked you. 😄 No worries, it happens.
